name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: ENV
          script_stop: true
          script: |
            cd /home/ubuntu/cicd-nest-test
            rm -rf .env
            git pull origin main
            echo "$ENV" > .env
            npm i
            npm run build
            pm2 kill
            pm2 start dist/main.js --name "backend-server"